"""initial schema

Revision ID: c2eda69cd4cf
Revises:
Create Date: 2026-09-01 20:33:30.751797

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2eda69cd4cf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=True)
    op.create_table(
        "events",
        sa.Column("vlr_event_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=True),
        sa.Column("tier", sa.String(length=32), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("season_year", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_vlr_event_id"), "events", ["vlr_event_id"], unique=True)
    op.create_table(
        "players",
        sa.Column("vlr_player_id", sa.Integer(), nullable=False),
        sa.Column("handle", sa.String(length=128), nullable=False),
        sa.Column("real_name", sa.String(length=256), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    op.create_index(op.f("ix_players_vlr_player_id"), "players", ["vlr_player_id"], unique=True)
    op.create_table(
        "teams",
        sa.Column("vlr_team_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("tag", sa.String(length=16), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("region", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    op.create_index(op.f("ix_teams_vlr_team_id"), "teams", ["vlr_team_id"], unique=True)
    op.create_table(
        "matches",
        sa.Column("vlr_match_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("team_a_id", sa.Uuid(), nullable=False),
        sa.Column("team_b_id", sa.Uuid(), nullable=False),
        sa.Column("winner_team_id", sa.Uuid(), nullable=True),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("best_of", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_matches_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_a_id"],
            ["teams.id"],
            name=op.f("fk_matches_team_a_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_b_id"],
            ["teams.id"],
            name=op.f("fk_matches_team_b_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["teams.id"],
            name=op.f("fk_matches_winner_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
    )
    op.create_index(op.f("ix_matches_event_id"), "matches", ["event_id"], unique=False)
    op.create_index(op.f("ix_matches_played_at"), "matches", ["played_at"], unique=False)
    op.create_index(op.f("ix_matches_team_a_id"), "matches", ["team_a_id"], unique=False)
    op.create_index(op.f("ix_matches_team_b_id"), "matches", ["team_b_id"], unique=False)
    op.create_index(op.f("ix_matches_vlr_match_id"), "matches", ["vlr_match_id"], unique=True)
    op.create_index(op.f("ix_matches_winner_team_id"), "matches", ["winner_team_id"], unique=False)
    op.create_table(
        "player_team_history",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_player_team_history_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_player_team_history_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_team_history")),
    )
    op.create_index(
        op.f("ix_player_team_history_player_id"), "player_team_history", ["player_id"], unique=False
    )
    op.create_index(
        "ix_player_team_history_player_id_is_current",
        "player_team_history",
        ["player_id", "is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_team_history_team_id"), "player_team_history", ["team_id"], unique=False
    )
    op.create_table(
        "match_maps",
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("map_number", sa.Integer(), nullable=False),
        sa.Column("map_name", sa.String(length=64), nullable=False),
        sa.Column("team_a_score", sa.Integer(), nullable=True),
        sa.Column("team_b_score", sa.Integer(), nullable=True),
        sa.Column("winner_team_id", sa.Uuid(), nullable=True),
        sa.Column("rounds_played", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_maps_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["teams.id"],
            name=op.f("fk_match_maps_winner_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_maps")),
        sa.UniqueConstraint("match_id", "map_number", name="uq_match_maps_match_id_map_number"),
    )
    op.create_index(op.f("ix_match_maps_match_id"), "match_maps", ["match_id"], unique=False)
    op.create_index(
        op.f("ix_match_maps_winner_team_id"), "match_maps", ["winner_team_id"], unique=False
    )
    op.create_table(
        "player_map_stats",
        sa.Column("match_map_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("rounds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("kills", sa.Integer(), server_default="0", nullable=False),
        sa.Column("deaths", sa.Integer(), server_default="0", nullable=False),
        sa.Column("assists", sa.Integer(), server_default="0", nullable=False),
        sa.Column("first_kills", sa.Integer(), server_default="0", nullable=False),
        sa.Column("first_deaths", sa.Integer(), server_default="0", nullable=False),
        sa.Column("adr", sa.Float(), nullable=True),
        sa.Column("kast_pct", sa.Float(), nullable=True),
        sa.Column("clutch_wins", sa.Integer(), nullable=True),
        sa.Column("clutch_attempts", sa.Integer(), nullable=True),
        sa.Column("acs", sa.Float(), nullable=True),
        sa.Column("vlr_rating", sa.Float(), nullable=True),
        sa.Column("headshot_pct", sa.Float(), nullable=True),
        sa.Column("max_kills", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_player_map_stats_agent_id_agents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["match_map_id"],
            ["match_maps.id"],
            name=op.f("fk_player_map_stats_match_map_id_match_maps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_player_map_stats_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_player_map_stats_team_id_teams"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_map_stats")),
        sa.UniqueConstraint(
            "match_map_id", "player_id", name="uq_player_map_stats_match_map_id_player_id"
        ),
    )
    op.create_index(
        op.f("ix_player_map_stats_agent_id"), "player_map_stats", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_map_stats_match_map_id"), "player_map_stats", ["match_map_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_map_stats_player_id"), "player_map_stats", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_map_stats_team_id"), "player_map_stats", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_map_stats_team_id"), table_name="player_map_stats")
    op.drop_index(op.f("ix_player_map_stats_player_id"), table_name="player_map_stats")
    op.drop_index(op.f("ix_player_map_stats_match_map_id"), table_name="player_map_stats")
    op.drop_index(op.f("ix_player_map_stats_agent_id"), table_name="player_map_stats")
    op.drop_table("player_map_stats")
    op.drop_index(op.f("ix_match_maps_winner_team_id"), table_name="match_maps")
    op.drop_index(op.f("ix_match_maps_match_id"), table_name="match_maps")
    op.drop_table("match_maps")
    op.drop_index(op.f("ix_player_team_history_team_id"), table_name="player_team_history")
    op.drop_index("ix_player_team_history_player_id_is_current", table_name="player_team_history")
    op.drop_index(op.f("ix_player_team_history_player_id"), table_name="player_team_history")
    op.drop_table("player_team_history")
    op.drop_index(op.f("ix_matches_winner_team_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_vlr_match_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_team_b_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_team_a_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_played_at"), table_name="matches")
    op.drop_index(op.f("ix_matches_event_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_teams_vlr_team_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_players_vlr_player_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_events_vlr_event_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_agents_name"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
